version: '3'

volumes:
  hub_data: {}
  hub_logs: {}
  hub_config: {}

services:
  openbadge-hub-py:
    restart: always
    build:
      context: .
      dockerfile: ./compose/openbadge-hub-py/Dockerfile_jessie_prod
    volumes:
      - hub_data:/data
      - hub_logs:/logs
      - hub_config:/config
      - /sys/kernel/debug:/sys/kernel/debug
    entrypoint: ./badge_hub.py
    command: -m server pull
    env_file: .env
    privileged: true
    network_mode: "host"

  aws-backup:
    build:
      context: .
      dockerfile: ./compose/aws-backup/Dockerfile
    env_file: .env
    volumes:
      - hub_data:/data:ro
      - hub_logs:/logs:ro
    restart: always
    entrypoint: ./entrypoint.sh
    network_mode: "host"
