# Based on - https://github.com/don41382/docker-rpi-python3-with-bluetooth
# Pull base image
FROM ubuntu
MAINTAINER Oren Lederman orenled@mit.edu

# Install dependencies
RUN apt-get update && apt-get install -y \
    python \
    python-dev \
    python-pip \
    python-setuptools \
    gcc \
    build-essential \
    libglib2.0-dev \
    bluez \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

ENV DATA_DIR /data
RUN mkdir $DATA_DIR

ENV LOG_DIR /logs
RUN mkdir $LOG_DIR

ENV CONFIG_DIR /config
RUN mkdir $CONFIG_DIR

COPY ./src/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Define working directory
WORKDIR /app

# Define default command
#CMD ["bash"]
#ENTRYPOINT ["./badge_hub.py"]
