FROM ubuntu:18.04
MAINTAINER Jordan Reedie jreedie@mit.edu
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    tzdata \
    python \
    python-pip \
    cron && \
    pip install awscli

COPY ./compose/aws-backup/entrypoint.sh /
COPY ./compose/aws-backup/backup.sh /

RUN chmod +x /entrypoint.sh /backup.sh
